use customer;

-- Q1. What is the total revenue generated by male vs. female customers

SELECT 
    gender, SUM(purchase_amount) AS Revenue
FROM
    customer.customer_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer_data
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased, ROUND(AVG(review_rating), 2) AS rating
FROM
    customer_data
GROUP BY item_purchased
ORDER BY rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    customer_data
WHERE
    shipping_type = 'standard'
        OR shipping_type = 'Express'
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers

SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_purchase_amount,
    SUM(purchase_amount) AS revenue
FROM
    customer_data
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased, COUNT(*) AS count
FROM
    customer_data
WHERE
    discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY count DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and sh

select customer_id , 
case 
when purchase_frequency_days in (365,90) then "New"
when purchase_frequency_days in (14,30)  then "Returning"
when purchase_frequency_days = 7  then "Loyal"
End as customer_segment
from customer_data;

-- Q8. What are the top 3 most purchased products within each category?

select * from (select item_purchased , category ,count(*) as count, dense_rank() over(partition by category order by count(*) desc) as ranks from customer_data group by item_purchased , category ) t where ranks <=3 order by count desc,category;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?



-- Q10. What is the revenue contribution of each age group?

